package common

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"doujia/internal/agent/core"
	"doujia/internal/agent/llm"
)

type testHandlerRegistry struct {
	handlers map[string]core.Handler
}

func (r testHandlerRegistry) Get(name string) (core.Handler, bool) {
	handler, ok := r.handlers[name]
	return handler, ok
}

type testHandler struct {
	name       string
	handleFunc func(context.Context, core.HandlerRequest) (core.HandlerResponse, error)
}

func (h testHandler) Name() string { return h.name }

func (h testHandler) Description() string { return h.name }

func (h testHandler) ToolSpec() core.ToolSpec { return core.ToolSpec{Name: h.name} }

func (h testHandler) Handle(ctx context.Context, req core.HandlerRequest) (core.HandlerResponse, error) {
	if h.handleFunc == nil {
		return core.HandlerResponse{}, fmt.Errorf("unexpected handle for %s", h.name)
	}
	return h.handleFunc(ctx, req)
}

type testLLM struct {
	response string
	err      error
}

func (l testLLM) Chat(context.Context, llm.ChatRequest) (llm.ChatResponse, error) {
	if l.err != nil {
		return llm.ChatResponse{}, l.err
	}
	return llm.ChatResponse{
		Message: llm.Message{
			Role:    "assistant",
			Content: l.response,
		},
	}, nil
}

func TestBuildUpstreamArtifactIssueResultUsesLLMContentWhenAvailable(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	spec := core.OpSpec{
		ExpectedOutputs: []core.OutputSpec{
			{
				LogicalKey: core.LKUpstreamArtifactIssue,
				ObjectType: "markdown",
				FileName:   "upstream_artifact_issue.md",
				Required:   false,
			},
		},
	}
	writeHandler := testHandler{
		name: "artifact_write",
		handleFunc: func(_ context.Context, req core.HandlerRequest) (core.HandlerResponse, error) {
			content, _ := req.Args["content"].(string)
			path := filepath.Join(req.Bundle.OutputDir, "upstream_artifact_issue.md")
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return core.HandlerResponse{}, err
			}
			return core.HandlerResponse{
				Data: map[string]any{
					"object_type": "markdown",
					"status":      "produced",
					"path":        path,
				},
			}, nil
		},
	}

	result, err := BuildUpstreamArtifactIssueResult(context.Background(), core.AgentRunRequest{
		Task:   core.Task{Role: "coder", Op: "write_code", AgentID: "coder01"},
		Bundle: core.AgentInputBundle{OutputDir: outputDir},
		OpSpec: spec,
		LLM:    testLLM{response: "# LLM Issue\n\nGenerated by model.\n"},
		Handlers: testHandlerRegistry{handlers: map[string]core.Handler{
			"artifact_write": writeHandler,
		}},
	}, UpstreamArtifactIssueParams{
		ProblemLogicalKey: "module_spec",
		ProblemFile:       "module_spec.json",
		Problem:           "module_spec.json is missing required field branch_name.",
		WhyBlocked:        "coder.write_code cannot prepare a worktree without branch_name.",
		SuggestedRepair:   "Repair or rerun architect.split_module.",
	})
	if err != nil {
		t.Fatalf("BuildUpstreamArtifactIssueResult() error = %v", err)
	}
	if result.Result != "kbug" {
		t.Fatalf("BuildUpstreamArtifactIssueResult() result = %q, want kbug", result.Result)
	}
	body, readErr := os.ReadFile(filepath.Join(outputDir, "upstream_artifact_issue.md"))
	if readErr != nil {
		t.Fatalf("ReadFile() error = %v", readErr)
	}
	if got := string(body); !strings.Contains(got, "Generated by model.") {
		t.Fatalf("upstream_artifact_issue.md = %q, want LLM content", got)
	}
}

func TestBuildUpstreamArtifactIssueResultFallsBackToTemplateWhenLLMFails(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	spec := core.OpSpec{
		ExpectedOutputs: []core.OutputSpec{
			{
				LogicalKey: core.LKUpstreamArtifactIssue,
				ObjectType: "markdown",
				FileName:   "upstream_artifact_issue.md",
				Required:   false,
			},
		},
	}
	writeHandler := testHandler{
		name: "artifact_write",
		handleFunc: func(_ context.Context, req core.HandlerRequest) (core.HandlerResponse, error) {
			content, _ := req.Args["content"].(string)
			path := filepath.Join(req.Bundle.OutputDir, "upstream_artifact_issue.md")
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return core.HandlerResponse{}, err
			}
			return core.HandlerResponse{
				Data: map[string]any{
					"object_type": "markdown",
					"status":      "produced",
					"path":        path,
				},
			}, nil
		},
	}

	result, err := BuildUpstreamArtifactIssueResult(context.Background(), core.AgentRunRequest{
		Task:   core.Task{Role: "tester", Op: "test_code", AgentID: "tester01"},
		Bundle: core.AgentInputBundle{OutputDir: outputDir},
		OpSpec: spec,
		LLM:    testLLM{err: fmt.Errorf("llm unavailable")},
		Handlers: testHandlerRegistry{handlers: map[string]core.Handler{
			"artifact_write": writeHandler,
		}},
	}, UpstreamArtifactIssueParams{
		ProblemLogicalKey: "coder_branch",
		ProblemFile:       "coder_branch.json",
		Problem:           "coder_branch.json is missing required field commit.",
		WhyBlocked:        "tester.test_code cannot run module tests without the tested commit.",
		SuggestedRepair:   "Repair or rerun coder.write_code.",
	})
	if err != nil {
		t.Fatalf("BuildUpstreamArtifactIssueResult() error = %v", err)
	}
	if result.Result != "kbug" {
		t.Fatalf("BuildUpstreamArtifactIssueResult() result = %q, want kbug", result.Result)
	}
	body, readErr := os.ReadFile(filepath.Join(outputDir, "upstream_artifact_issue.md"))
	if readErr != nil {
		t.Fatalf("ReadFile() error = %v", readErr)
	}
	got := string(body)
	if !strings.Contains(got, "# Upstream Artifact Issue") {
		t.Fatalf("upstream_artifact_issue.md = %q, want template heading", got)
	}
	if !strings.Contains(got, "coder_branch.json is missing required field commit.") {
		t.Fatalf("upstream_artifact_issue.md = %q, want problem details", got)
	}
}
