package coder

import (
	"fmt"
	"strings"

	"devflow/internal/agent/common"
	"devflow/internal/agentengine"
	"devflow/internal/core"
)

func buildPrompt(task core.TaskMetaData, recipe Recipe, inputs writeCodeInputs) string {
	var builder strings.Builder
	builder.WriteString("# Role\n")
	builder.WriteString(recipe.SystemPrompt)
	builder.WriteString("\n\n# Task\n")
	builder.WriteString(fmt.Sprintf("task_id: %s\n", task.TaskID))
	builder.WriteString(fmt.Sprintf("agent_id: %s\n", task.AgentID))
	builder.WriteString(fmt.Sprintf("op: %s\n", task.Op))
	builder.WriteString("\n# Goal\n")
	builder.WriteString(recipe.Description)
	builder.WriteString("\n\n# Inputs\n")
	writeDoc(&builder, inputs.moduleDoc)
	writeDoc(&builder, inputs.branchDoc)
	writeDoc(&builder, inputs.contractDoc)
	writeDoc(&builder, inputs.seedDoc)
	builder.WriteString("\n# Instructions\n")
	builder.WriteString(recipe.UserInstruction)
	builder.WriteString("\n\n# Runtime Contract\n")
	builder.WriteString("1. You are already inside the coder git worktree.\n")
	builder.WriteString("2. Do not run git checkout, git merge, or git commit.\n")
	builder.WriteString("3. Do not modify the main branch worktree.\n")
	builder.WriteString("4. Write a JSON execution report to .devflow/result.json.\n")
	builder.WriteString("5. The report must include status, summary, changed_files, test_command, and test_passed.\n")
	builder.WriteString("6. test_command must be one executable shell command string. Do not include prose, Markdown, explanations, or phrases like \"smoke test covering\" in test_command.\n")
	builder.WriteString("7. Put test explanations in summary, not in test_command.\n")
	builder.WriteString("8. You must implement according to module_contract.json.\n")
	builder.WriteString("9. You must satisfy seed_tests.json.\n")
	builder.WriteString("10. Do not invent public APIs.\n")
	builder.WriteString("11. Do not modify seed test files.\n")
	builder.WriteString("12. Only modify files allowed by module_contract.json.\n")
	builder.WriteString("13. Do not modify forbidden files.\n")
	builder.WriteString("14. Do not claim test_passed=true unless the official seed test command exits with code 0 in this worktree.\n")
	builder.WriteString("15. If module_contract.delivery_profile is frontend_web, produce the complete browser app entry: index.html must load code from src, README.md must contain real run instructions, and the result must not be only module functions.\n")
	builder.WriteString("16. For frontend_web delivery, implement every required_file in module_contract.json and keep index.html connected to the src application code.\n")
	builder.WriteString("17. Example report: {\"status\":\"completed\",\"summary\":\"Implemented module contract API.\",\"changed_files\":[\"src/module.js\"],\"test_command\":\"node test/module01.seed.test.js\",\"test_passed\":true}\n")
	return builder.String()
}

func buildBriefPrompt(task core.TaskMetaData, recipe Recipe, briefContent string) string {
	var builder strings.Builder
	builder.WriteString("# Role\n")
	builder.WriteString(recipe.SystemPrompt)
	builder.WriteString("\n\n# Task\n")
	builder.WriteString(fmt.Sprintf("task_id: %s\n", task.TaskID))
	builder.WriteString(fmt.Sprintf("agent_id: %s\n", task.AgentID))
	builder.WriteString(fmt.Sprintf("op: %s\n", task.Op))
	builder.WriteString("\n# Goal\n")
	builder.WriteString(recipe.Description)
	builder.WriteString("\n\n# Implementation Brief\n")
	builder.WriteString(strings.TrimSpace(briefContent))
	builder.WriteString("\n\n# Instructions\n")
	builder.WriteString(recipe.UserInstruction)
	builder.WriteString("\n\n# Runtime Contract\n")
	builder.WriteString("1. You are already inside the coder git worktree.\n")
	builder.WriteString("2. Use the implementation brief as the primary source.\n")
	builder.WriteString("3. Do not read every context file first.\n")
	builder.WriteString("4. Read .devflow/context/context_refs.json only when the brief is insufficient.\n")
	builder.WriteString("5. Do not run git checkout, git merge, or git commit.\n")
	builder.WriteString("6. Do not modify the main branch worktree.\n")
	builder.WriteString("7. Do not modify files outside allowed_files.\n")
	builder.WriteString("8. Do not modify forbidden_files.\n")
	builder.WriteString("9. Do not invent public APIs.\n")
	builder.WriteString("10. Do not modify seed test files.\n")
	builder.WriteString("11. Write a JSON execution report to .devflow/result.json after finishing.\n")
	builder.WriteString("12. The report must include at least status, summary, changed_files, test_command, test_passed, context_files_read, assumptions, and known_issues.\n")
	builder.WriteString("13. test_command must be one executable shell command string. Do not include prose, Markdown, explanations, or phrases like \"smoke test covering\" in test_command.\n")
	builder.WriteString("14. Put test explanations in summary, not in test_command.\n")
	builder.WriteString("15. Do not claim test_passed=true unless the official seed test command exits with code 0 in this worktree.\n")
	builder.WriteString("16. If delivery_profile is frontend_web, produce the complete browser app entry: index.html must load code from src, README.md must contain real run instructions, and the result must not be only module functions.\n")
	builder.WriteString("17. For frontend_web delivery, implement every required_file and keep index.html connected to the src application code.\n")
	builder.WriteString("18. Example report: {\"status\":\"completed\",\"summary\":\"Implemented module contract API.\",\"changed_files\":[\"src/module.js\"],\"test_command\":\"node test/module01.seed.test.js\",\"test_passed\":true,\"context_files_read\":[],\"assumptions\":[],\"known_issues\":[]}\n")
	return builder.String()
}

func buildDebugBriefPrompt(task core.TaskMetaData, recipe Recipe, briefContent string) string {
	var builder strings.Builder
	builder.WriteString("# Debug Existing Coder Branch\n\n")
	builder.WriteString("# Role\n")
	builder.WriteString(recipe.SystemPrompt)
	builder.WriteString("\n\n# Task\n")
	builder.WriteString(fmt.Sprintf("task_id: %s\n", task.TaskID))
	builder.WriteString(fmt.Sprintf("agent_id: %s\n", task.AgentID))
	builder.WriteString(fmt.Sprintf("op: %s\n", task.Op))
	builder.WriteString("\n# Goal\n")
	builder.WriteString(recipe.Description)
	builder.WriteString("\n\n# Debug Brief\n")
	builder.WriteString(strings.TrimSpace(briefContent))
	builder.WriteString("\n\n# Instructions\n")
	builder.WriteString(recipe.UserInstruction)
	builder.WriteString("\n\n# Runtime Contract\n")
	builder.WriteString("1. You are already inside the existing coder branch worktree.\n")
	builder.WriteString("2. Use the debug brief as the primary repair source.\n")
	builder.WriteString("3. If the failure cause, original requirement, or contract boundary is unclear, read .devflow/context/debug_refs.json and then read only the referenced files you need.\n")
	builder.WriteString("4. Do not run git checkout, git merge, or git commit. Do not switch branches.\n")
	builder.WriteString("5. Do not modify the main branch worktree.\n")
	builder.WriteString("6. Do not modify seed or full test files.\n")
	builder.WriteString("7. Do not invent public APIs or change the module contract.\n")
	builder.WriteString("8. Only modify allowed_files; do not modify forbidden_files.\n")
	builder.WriteString("9. Fix the root cause in product code.\n")
	builder.WriteString("10. Write a JSON execution report to .devflow/result.json after finishing.\n")
	builder.WriteString("11. The report must include status, summary, changed_files, test_command, test_passed, context_files_read, assumptions, and known_issues.\n")
	builder.WriteString("12. test_command must be one executable shell command string. Do not include prose, Markdown, explanations, or phrases like \"smoke test covering\" in test_command.\n")
	builder.WriteString("13. Put test explanations in summary, not in test_command.\n")
	builder.WriteString("14. Do not claim test_passed=true unless the required command passes in this worktree.\n")
	builder.WriteString("15. If delivery_profile is frontend_web, preserve a real browser app entry: index.html must load code from src, README.md must contain real run instructions, and required_files must exist.\n")
	builder.WriteString("16. Example report: {\"status\":\"completed\",\"summary\":\"Fixed failing behavior in product code.\",\"changed_files\":[\"src/module.js\"],\"test_command\":\"node test/module01.seed.test.js\",\"test_passed\":true,\"context_files_read\":[\".devflow/context/failure_report.md\"],\"assumptions\":[],\"known_issues\":[]}\n")
	return builder.String()
}

func writeDoc(builder *strings.Builder, doc agentengine.ArtifactDocument) {
	builder.WriteString("\n---\n")
	builder.WriteString(fmt.Sprintf("source: %s\n", doc.URI))
	builder.WriteString(doc.Content)
	builder.WriteString("\n")
}

func buildDebugPrompt(task core.TaskMetaData, recipe Recipe, inputs debugInputs, branchInfo common.CoderBranchArtifact, testCommand string) string {
	var builder strings.Builder
	builder.WriteString("# Debug Existing Coder Branch\n\n")
	builder.WriteString("# Role\n")
	builder.WriteString(recipe.SystemPrompt)
	builder.WriteString("\n\n# Task\n")
	builder.WriteString(fmt.Sprintf("task_id: %s\n", task.TaskID))
	builder.WriteString(fmt.Sprintf("agent_id: %s\n", task.AgentID))
	builder.WriteString(fmt.Sprintf("op: %s\n", task.Op))
	builder.WriteString("\n# Goal\n")
	builder.WriteString(recipe.Description)
	builder.WriteString("\n\n# Branch Under Repair\n")
	builder.WriteString(fmt.Sprintf("- repo_dir: %s\n", branchInfo.RepoDir))
	builder.WriteString(fmt.Sprintf("- branch: %s\n", branchInfo.Branch))
	builder.WriteString(fmt.Sprintf("- commit: %s\n", branchInfo.Commit))
	builder.WriteString(fmt.Sprintf("- worktree: %s\n", branchInfo.Worktree))
	builder.WriteString(fmt.Sprintf("- tester_reported_command_for_context: %s\n", testCommand))
	builder.WriteString("\n# Inputs\n")
	writeNamedDoc(&builder, "Module Task", inputs.moduleDoc)
	writeNamedDoc(&builder, "Coder Branch Artifact", inputs.branchDoc)
	writeNamedDoc(&builder, "Module Contract", inputs.contractDoc)
	writeNamedDoc(&builder, "Seed Tests", inputs.seedDoc)
	if strings.TrimSpace(inputs.fullTestsDoc.URI) != "" {
		writeNamedDoc(&builder, "Full Test Files", inputs.fullTestsDoc)
	}
	writeNamedDoc(&builder, "Test Failure Report", inputs.failureDoc)
	builder.WriteString("\n# Instructions\n")
	builder.WriteString(recipe.UserInstruction)
	builder.WriteString("\n\n# Runtime Contract\n")
	builder.WriteString("1. You are already inside the existing coder branch worktree.\n")
	builder.WriteString("2. Do not run git checkout, git merge, or git commit.\n")
	builder.WriteString("3. Do not modify the main branch worktree.\n")
	builder.WriteString("4. Read the failure report, then fix the root cause in product code.\n")
	builder.WriteString("5. Write a JSON execution report to .devflow/result.json.\n")
	builder.WriteString("6. The report must include status, summary, changed_files, test_command, and test_passed.\n")
	builder.WriteString("7. test_command must be one executable shell command string. Do not include prose, Markdown, explanations, or phrases like \"smoke test covering\" in test_command.\n")
	builder.WriteString("8. Put test explanations in summary, not in test_command.\n")
	builder.WriteString("9. Do not modify seed or full test files.\n")
	builder.WriteString("10. Do not invent new public APIs or change the module contract.\n")
	builder.WriteString("11. Do not invent new test commands. Preserve the suggested command for handoff metadata when relevant, but keep verification responsibility with the runtime.\n")
	builder.WriteString("12. Do not claim test_passed=true unless the required runtime-provided command succeeds in this worktree.\n")
	builder.WriteString("13. If module_contract.delivery_profile is frontend_web, preserve a real browser app entry: index.html must load code from src, README.md must contain real run instructions, and required_files must exist.\n")
	return builder.String()
}

func writeNamedDoc(builder *strings.Builder, title string, doc agentengine.ArtifactDocument) {
	builder.WriteString("\n---\n")
	builder.WriteString(title)
	builder.WriteString("\nsource: ")
	builder.WriteString(doc.URI)
	builder.WriteString("\n")
	builder.WriteString(doc.Content)
	builder.WriteString("\n")
}
